version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - dependabot
  ignore:
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: jsdoc-to-markdown
    versions:
    - 7.0.1
  - dependency-name: openid-client
    versions:
    - 4.5.2
    - 4.6.0
